#!/usr/bin/python3


import sys
import time



def fact(nb):
	for e in range(2, int(nb ** 0.5) + 1):
		if nb % e == 0:
			return e, nb // e
	return None


if __name__ == "__main__":
	if len(sys.argv) != 2:
		print("Usage: factors <file>")
		exit()

	input_file = sys.argv[1]

	try:
		with open(input_file, 'r') as f:
			lns = f.readlines()
	except FileNotFoundError:
		print("File not found")
		exit()

	start_time = time.time()
	for l in lns:
		n = int(l.strip())
		factors = fact(n)
		if factors:
			print(f"{n}={factors[1]}*{factors[0]}")
		if time.time() - start_time > 5:
			print("Time limit exceeded")
			exit()
