#!/usr/bin/python3
import sys
import time



def fact(nbrs):
	for j in range(2, int(nbrs ** 0.5) + 1):
		if nbrs % j == 0:
			return j, nbrs // j
	return None


if __name__ == "__main__":
	if len(sys.argv) != 2:
		print("Usage: factors <file>")
		exit()

	input_file = sys.argv[1]

	try:
		with open(input_file, 'r') as f:
			lines = f.readlines()
	except FileNotFoundError:
		print("File not found")
		exit()

	start_time = time.time()
	for line in lines:
		nbr = int(line.strip())
		factors = fact(nbr)
		if factors:
			print(f"{num}={factors[0]}*{factors[1]}")
		if time.time() - start_time > 5:
			print("Time limit exceeded")
			exit()
